name: Build

on: push
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Check codestyle
      run: git ls-files *.[c,h] | xargs clang-format -i --verbose && git diff --exit-code
    - name: Build applications
      run: make
    - name: Build tests
      run: make test
    - name: Run tests
      run: make test_run
    - name: Clean
      run: make clean
